# Generated by Django 4.0.4 on 2022-08-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userIssue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='售卖价格')),
                ('issuedate', models.DateTimeField(db_column='issueDate', verbose_name='发布时间')),
                ('buy_price', models.FloatField(blank=True, null=True, verbose_name='购入价格')),
                ('introduction', models.CharField(blank=True, max_length=255, verbose_name='介绍')),
                ('imagefile', models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='图片')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userIssue.userissue')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='MessageCompose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagedate', models.DateTimeField(db_column='messageDate', verbose_name='留言时间')),
                ('content', models.TextField(db_column='content', max_length=255, verbose_name='留言内容')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsIssue.goodsissue')),
                ('owner', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='userIssue.userissue')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '商品留言',
            },
        ),
        migrations.CreateModel(
            name='MessageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagedate', models.DateTimeField(db_column='messageDate', verbose_name='留言时间')),
                ('content', models.TextField(db_column='content', max_length=255, verbose_name='留言内容')),
                ('owner', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='userIssue.userissue')),
                ('reply_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsIssue.messagecompose')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='userIssue.userissue')),
            ],
            options={
                'verbose_name': '留言的评论',
                'verbose_name_plural': '留言评论',
            },
        ),
    ]
