# Generated by Django 4.0.4 on 2022-08-17 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True, verbose_name='学号')),
                ('passwd', models.CharField(max_length=255, verbose_name='密码')),
                ('name', models.CharField(max_length=255, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='头像')),
                ('signature', models.CharField(blank=True, max_length=255, verbose_name='个性签名')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagedate', models.DateTimeField(db_column='messageDate', verbose_name='私聊时间')),
                ('content', models.TextField(db_column='content', max_length=255, verbose_name='私聊内容')),
                ('isRead', models.BooleanField(db_column='isRead', default=False, verbose_name='已读？')),
                ('pm_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_from', to='userIssue.user', verbose_name='发信人')),
                ('pm_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_to', to='userIssue.user', verbose_name='收信人')),
            ],
            options={
                'verbose_name': '私聊信息',
                'verbose_name_plural': '私聊信息',
            },
        ),
    ]
