# Generated by Django 4.0.4 on 2022-08-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsIssue', '0001_initial'),
        ('userIssue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIssue',
            new_name='User',
        ),
    ]
